# Introdução à Data Science com Python - Data ICMC-USP

Esse material foi desenvolvido pelo Data, grupo de extensão de aprendizado e ciência de dados compostos por alunos do Instituto de Ciências Matemáticas e de Computação da USP.

Esse notebook é acompanhado de um curso em video, que pode ser encontrado em [aqui](https://www.youtube.com/playlist?list=PLFE-LjWAAP9SfEuLXf3qrpw4szKWjlYq9)

Para saber mais sobre as atividades do Data entre no nosso site e nos siga e nossas redes sociais:
- [Site](http://data.icmc.usp.br/)
- [Twitter](https://twitter.com/data_icmc)
- [LinkedIn](https://www.linkedin.com/school/data-icmc/)
- [Facebook](https://www.facebook.com/dataICMC/)

Aproveite o material!

## Exercícios Python

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos nas aulas de Python. Esse material foi preparado para acompanhar o que foi passado nos videos, e em breve teremos a divulgação das resuluções com um vídeo de explicação.

### Variáveis

In [1]:
# Declare uma variavel chamada a e atribua o valor 10 a ela
a = 10

In [2]:
# Imprime essa variavel que você acabou de criar
# * PRIMEIRA MANEIRA * :
a

10

In [3]:
# * SEGUNDA MANEIRA * #
print(a)

10


In [4]:
# Crie uma outra variavel b que recebe o valor de a so que como string
# * Converter a variável "a" para string
a = "10"
# * Variável "b" recebe "a" como string
b = a
print("Variável b = ", b)
type(b)

Variável b =  10


str

In [5]:
# Combine sua variavel b a variavel abaixo para obter a string "Hello 10" em uma variavel d
c = "Hello "
# * Concatenando as string:
d = c + b
type(d)

str

In [7]:
# Imprima a variável d
print(d)

Hello 10


In [9]:
d

'Hello 10'

### Strings

In [10]:
my_str = 'Insira uma frase aqui!'

In [11]:
# Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)
my_str_new = my_str.replace("!", "?")
my_str_new

'Insira uma frase aqui?'

In [12]:
# Crie uma lista "my_words" com cada palavra a frase
my_words = ['I', 'n', 's', 'i', 'r', 'a', 'u', 'm', 'a', 'f', 'r', 'a', 's', 'e', 'a', 'q', 'u', 'i', '!']
print(my_words)

['I', 'n', 's', 'i', 'r', 'a', 'u', 'm', 'a', 'f', 'r', 'a', 's', 'e', 'a', 'q', 'u', 'i', '!']


### Listas

In [13]:
lista = [1, 23, 31, 40, 56, 16]

In [14]:
# Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)
for elemento in lista:
    print(elemento)

1
23
31
40
56
16


In [15]:
# Faça um for que imprima o dobro de cada elemento da lista "lista" 
for elemento in lista:
    print(elemento * 2)

2
46
62
80
112
32


In [16]:
# Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension

In [17]:
# Crie uma nova lista chamada "pares"
pares = []
# Faça um for que itetere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
for elemento in lista:
    if (elemento%2 == 0):
        pares.append(elemento)
# Imprima a lista "pares"
print(pares)

[40, 56, 16]


In [18]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [19]:
# Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())
for elemento in lista2:
    tipo = type(elemento)
    if (tipo == str):
        print(elemento)

oi
top
python


#### Indexando

In [20]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [21]:
# Selecione o ultimo elemento da lista

In [22]:
# * PRIMEIRA FORMA * #
ultimo_elemento = my_list[7]
print(ultimo_elemento)

70


In [23]:
# * SEGUNDA FORMA * #
ultimo_elemento = my_list[-1]
ultimo_elemento

70

In [24]:
# Selecione do primeiro até o 4 elemento da lista
select = my_list[0:4]
print(select)

[0, 10, 20, 30]


In [25]:
# Selecione do segundo elemento da lista até o quinto
select = my_list[1:5]
print(select)

[10, 20, 30, 40]


In [26]:
# Selecione do primeiro elemento da lista até o penultimo
select = my_list[0:-1]
print(select)

[0, 10, 20, 30, 40, 50, 60]


### Dicionários

In [27]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [28]:
# Crie um dicionario que contenha a contagem de cada elemento do vetor
my_dict = {'a': lista.count('a'), 'b': lista.count('b'), 'c': lista.count('c'), 'd': lista.count('d'), 'e': lista.count('e')}
#...

In [29]:
print(my_dict)

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}


### Funções

In [30]:
# Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    soma = sum(lista)
    return soma

In [31]:
soma_elementos([1, 2, 3, 4, 5])

15

In [32]:
soma_elementos([-1, 5, 7, -2])

9

In [33]:
# Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip
def produto_escalar(lista_1, lista_2):
    # * Contando o número de elementos da primeira lista:
    num_elementos = len(lista_1)
    produto = list(zip(lista_1, lista_2))
    
    contador = 0
    lista_multiplicacao = []
    while (contador < num_elementos):
        multiplicacao = (produto[contador][0])*(produto[contador][1])
        lista_multiplicacao.append(multiplicacao)
        contador += 1

    print(lista_multiplicacao)
    
    produto_escalar_calculado = sum(lista_multiplicacao)
    print("Produto escalar = ", produto_escalar_calculado)

In [34]:
produto_escalar([1, 2, 3], [0, 4, 7])

[0, 8, 21]
Produto escalar =  29


In [35]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

[230, 80, 80, 1]
Produto escalar =  391


In [36]:
# Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par

def par_ou_impar(n):
    while (n>=1):
        teste_par_ou_impar = n % 2
        if (teste_par_ou_impar == 0):
            print(n, "Par")
        else:
            print(n, "Ímpar")
        n = n - 1

In [37]:
par_ou_impar(15)

15 Ímpar
14 Par
13 Ímpar
12 Par
11 Ímpar
10 Par
9 Ímpar
8 Par
7 Ímpar
6 Par
5 Ímpar
4 Par
3 Ímpar
2 Par
1 Ímpar


In [38]:
par_ou_impar(15)

15 Ímpar
14 Par
13 Ímpar
12 Par
11 Ímpar
10 Par
9 Ímpar
8 Par
7 Ímpar
6 Par
5 Ímpar
4 Par
3 Ímpar
2 Par
1 Ímpar


In [39]:
# Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)

def diga_indice(lista):
    saida = list(enumerate(lista))
    return (saida)

In [40]:
diga_indice(['1', '2', '3'])

[(0, '1'), (1, '2'), (2, '3')]

In [41]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e')]

## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

In [42]:
# Importando a biblioteca
import numpy as np

### Arrays

In [43]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [44]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta
dimensao_a = np.shape(a)
dimensao_b = np.shape(b)
dimensao_c = np.shape(c)
print("Shape a = ", dimensao_a, "\nShape b = ", dimensao_b, "\nShape c = ", dimensao_c)

Shape a =  (7,) 
Shape b =  (2, 4) 
Shape c =  (3, 4)


In [45]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb

In [46]:
# Crie um array de uns com shape (4, 5)
array_uns = np.ones((4,5))
print(array_uns)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
array_77 = np.ones((4,2))
array_77 = array_77 * 77
print(array_77)

[[77. 77.]
 [77. 77.]
 [77. 77.]
 [77. 77.]]


In [48]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]
my_sequence = np.arange(0, 101, 1)
print(my_sequence, f'\n\n{type(my_sequence)}')

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100] 

<class 'numpy.ndarray'>


### Indexando

In [49]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[33 49 39 21  5  2  4 26 27 39 28  4  0 48 20]


In [50]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
slice_my_array = my_array[4:11]
slice_my_array

array([ 5,  2,  4, 26, 27, 39, 28])

In [51]:
# Selecione todos os elementos maiores que 20
select_my_array = my_array > 20
select_my_array_maior_20 = my_array[select_my_array]
print(select_my_array, f'\n\n{select_my_array_maior_20}')

[ True  True  True  True False False False  True  True  True  True False
 False  True False] 

[33 49 39 21 26 27 39 28 48]


In [52]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [53]:
# Selecione o elemento na primeira linha da terceira coluna
select_one_my_matrix = my_matrix[0,2]
print(select_one_my_matrix)

3


In [54]:
# Selecione o elemento na primeira linha da ultima coluna
select_two_my_matrix = my_matrix[0, 3]
print(select_two_my_matrix)

4


In [55]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
slice_one_my_matrix = my_matrix[1:3, 1:3]
print(slice_one_my_matrix)

[[ 6  7]
 [10 11]]


In [56]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
slice_two_my_matrix = my_matrix[0:2, 1:4]
print(slice_two_my_matrix)

[[2 3 4]
 [6 7 8]]


In [57]:
# Selecione os elementos da ultima coluna inteira
select_three_my_matrix = my_matrix[:,3]
print(select_three_my_matrix)

[ 4  8 12 16]


In [58]:
# Selecione os elementos da 2a linha inteira
select_four_my_matrix = my_matrix[1, :]
print(select_four_my_matrix)

[5 6 7 8]


### Operações

In [59]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[9 8 2 0 8]


In [60]:
# Some 10 a todos os elementos de my_array
my_array_plus_10 = my_array + 10
print(my_array_plus_10)

[19 18 12 10 18]


In [61]:
# Multiplique todos os elementos de my_array por 4
my_array_mult_4 = my_array * 4
print(my_array_mult_4)

[36 32  8  0 32]


In [87]:
# Obtenha a soma de todos os elementos de my_array
my_array_plus_total = np.sum(my_array)
print(my_array_plus_total)

22


In [88]:
# Obtenha a média de todos os elementos de my_array
my_array_mean = np.mean(my_array)
print(my_array_mean)

4.4


In [97]:
# Obtenha o indice do maior elemento de my_array

In [90]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[8 2 4 6 6] 

[6 0 0 9 6]


In [63]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[2 3 2 2 7] 

[[2 6 9 7 7]
 [6 8 9 1 7]
 [3 1 1 9 4]
 [1 5 1 5 3]
 [5 6 1 6 6]
 [7 6 6 6 8]
 [9 1 4 1 4]
 [0 4 8 4 5]
 [5 3 3 3 3]
 [2 1 9 1 6]]


In [64]:
# Some my_array elemento por elemento em cada linha de my_other_array
# * Broadcasting * #
array_plus_each = my_array + my_other_array
print(array_plus_each)

[[ 4  9 11  9 14]
 [ 8 11 11  3 14]
 [ 5  4  3 11 11]
 [ 3  8  3  7 10]
 [ 7  9  3  8 13]
 [ 9  9  8  8 15]
 [11  4  6  3 11]
 [ 2  7 10  6 12]
 [ 7  6  5  5 10]
 [ 4  4 11  3 13]]


In [65]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[2 5 9 8]
 [3 0 0 6]
 [9 4 0 3]
 [0 9 0 7]
 [2 7 1 6]] 

[[6 3 7 0 2]
 [3 2 3 4 8]
 [1 4 7 5 2]
 [3 3 1 5 4]
 [4 2 8 8 0]
 [6 5 5 9 5]
 [6 7 7 1 6]
 [5 7 9 0 7]
 [5 2 6 1 0]
 [5 1 2 9 1]]


In [66]:
# Faça a multiplicação entre my_other_array e my_array
# * Erro - arrays com dimensões diferentes (número de linhas #s do de colunas)
array_mult = np.dot(my_array, my_other_array)

ValueError: shapes (5,4) and (10,5) not aligned: 4 (dim 1) != 10 (dim 0)

In [68]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)
my_other_array_plus = np.sum(my_other_array, axis = 1)
print(my_other_array_plus)

[18 20 19 16 22 30 27 28 14 18]


In [92]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[5 4 5 0]
 [9 8 8 0]
 [3 2 0 4]
 [0 4 5 4]
 [4 3 5 3]]


In [94]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)
my_array_new = my_array.reshape(20)
print(my_array_new)


[5 4 5 0 9 8 8 0 3 2 0 4 0 4 5 4 4 3 5 3]


In [95]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [96]:
# Gere a array anterior usando np.arange e a função reshape
array_born = np.arange(16)
print(array_born)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
